FROM ubuntu:22.04

RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

COPY libdpp-10.0.29-linux-x64.deb /libdpp-10.0.29-linux-x64.deb

RUN apt update && apt upgrade -y
RUN apt install -y \
    git \
    cmake \
    gcc \
    g++ \
    ./libdpp-10.0.29-linux-x64.deb \
    libjsoncpp-dev
